load_module /usr/local/nginx/modules/ngx_http_modsecurity_module.so;

worker_processes auto;

error_log /dev/stderr info;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;

    server {
        listen 8080;
        server_name _;

        modsecurity on;
        modsecurity_rules_file /etc/nginx/modsecurity/main.conf;

        location / {
            default_type text/plain;
            return 200 "Gateway is running\n";
        }
    }
}